apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-test
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
