apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-test
  namespace: test
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.57.104
    path: "/opt/data"
