apiVersion: v1
kind: Pod
metadata:
  labels:
    version: v1.0
  name: liveness-pod
spec:
  containers:
  - name: liveness-pod
    image: nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      httpGet:
        path: /index.html
        port: 80
      successThreshold: 1
      failureThreshold: 5
      timeoutSeconds: 3
