apiVersion: v1
kind: Pod
metadata:
  name: memory-test-01
  namespace: test
spec:
  containers:
  - name: memory-test
    image: polinux/stress
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "80Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
