apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-deployment
  labels:
    app: test-web
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-web
      version: v1
  template:
    metadata:
      labels:
        app: test-web
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

