spring:
  profiles:
    include: swagger
  data:
    mongodb:
      host: localhost
      auto-index-creation: true
      username: 'dev'
      password: '123456'
      port: 27017
      database: test
      authentication-database: admin
  jackson:
    serialization:
      INDENT_OUTPUT: true

