spring:
  swagger:
    enabled: true
    group-name: user-service
    base-package: org.akj.springboot
    version: 1.0.0
    title: micro-services
    description: sample user service backed by webflux + reactive mongo stream
    contact-name: Jamie Zhang
    contact-email: akjamie.zhang@pm.me
    contact-url: akjamie.zhang@pm.me
  application:
    name: @project.artifactId@
    version: @project.version@

