spring:
  profiles:
    active: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  sql:
    init:
      mode: always

security.auth:
  jwt:
    key-pair:
      store-pass: ${JWT_KEYPAIR_STOREPASS:Test1234}
      alias: ${JWT_KEYPAIR_ALIAS:internal-certs}
      file-path: ${JWT_KEYPAIR_PATH:keystore.p12}

