spring:
  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/gateway/user-service/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
#                redis-rate-limiter.requestedTokens: 1
      default-filters:
        - StripPrefix=1
    config:
      discovery:
        enabled: true
        service-id: config-service
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      enabled: true

  application:
    name: gateway
  config:
    import: 'optional:configserver:'
  redis:
    client-type: lettuce
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-wait: 15000
        enabled: true
        min-idle: 2
        max-active: 4
        max-idle: 4
    sentinel:
      master: mymaster
      nodes:
        - 127.0.0.1:26379
#  webflux:
#    base-path: ${server.servlet.context-path}


eureka:
  client:
    webclient:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
server:
  servlet:
    context-path: /gateway
