spring:
  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/gateway/user-service/**
      default-filters:
        - StripPrefix=1
    config:
      discovery:
        enabled: true
        service-id: config-service
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      enabled: true

  application:
    name: gateway
  config:
    import: 'optional:configserver:'

eureka:
  client:
    webclient:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
