apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-registry
  labels:
    app: service-registry-dep
spec:
  serviceName: eureka
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: akjamie/service-registry:2.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: INSTANCE_NAME
              value: ${HOSTNAME}.eureka
            - name: EURAKA_SERVICE_URL
              value: http://service-registry-0.dev.svc.it-meta.space:8761/eureka/,http://service-registry-1.eureka.dev.svc.it-meta.space:8761/eureka/
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
  labels:
    app: service-registry-svc
spec:
  clusterIP: None
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: service-registry
