eureka.client.service-url:
  defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://ec2-35-76-118-244.ap-northeast-1.compute.amazonaws.com:8761/eureka/}
#  defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full