eureka.client.service-url:
  defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full