spring:
  doc:
    enabled: true
    service-name: User Service
    description: sample user service backed by webflux + reactive mongo stream
    version: @project.version@
    base-path: org.akj.springboot

