apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    service: registry-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    service: registry-service