spring:
  swagger:
    enabled: true
    group-name: config-service
    base-package: org.akj.springboot
    title: micro-services
    description: sample config service backed by spring cloud config
    contact-name: Jamie Zhang
    contact-email: akjamie.zhang@pm.me
    contact-url: akjamie.zhang@pm.me
  app:
    name: @project.artifactId@
    version: @project.version@

