spring:
  application:
    name: config-service
    cloud:
      config:
        server:
          native:
            search-locations: file:${CONFIG_REPO_PATH:${config.local.root-path}}/apps/{application}
          bootstrap: true
  profiles:
    active: native

eureka.client.service-url:
  defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

config.local.root-path: /Users/jamie/IdeaProjects/spring-learn-series/devops-configs

server:
  port: 8888
